/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AySpinner {
    }
    interface AyStockFinder {
    }
    interface AyStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLAySpinnerElement extends Components.AySpinner, HTMLStencilElement {
    }
    var HTMLAySpinnerElement: {
        prototype: HTMLAySpinnerElement;
        new (): HTMLAySpinnerElement;
    };
    interface HTMLAyStockFinderElement extends Components.AyStockFinder, HTMLStencilElement {
    }
    var HTMLAyStockFinderElement: {
        prototype: HTMLAyStockFinderElement;
        new (): HTMLAyStockFinderElement;
    };
    interface HTMLAyStockPriceElement extends Components.AyStockPrice, HTMLStencilElement {
    }
    var HTMLAyStockPriceElement: {
        prototype: HTMLAyStockPriceElement;
        new (): HTMLAyStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "ay-spinner": HTMLAySpinnerElement;
        "ay-stock-finder": HTMLAyStockFinderElement;
        "ay-stock-price": HTMLAyStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface AySpinner {
    }
    interface AyStockFinder {
        "onAySymbolsSelected"?: (event: CustomEvent<string>) => void;
    }
    interface AyStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "ay-spinner": AySpinner;
        "ay-stock-finder": AyStockFinder;
        "ay-stock-price": AyStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ay-spinner": LocalJSX.AySpinner & JSXBase.HTMLAttributes<HTMLAySpinnerElement>;
            "ay-stock-finder": LocalJSX.AyStockFinder & JSXBase.HTMLAttributes<HTMLAyStockFinderElement>;
            "ay-stock-price": LocalJSX.AyStockPrice & JSXBase.HTMLAttributes<HTMLAyStockPriceElement>;
        }
    }
}
